name: Integration Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
  
      - name: Prepare JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
  
      - name: Grant permission to gradlew
        run: chmod +x gradlew
  
      - name: Execute build and Test
        run: ./gradlew build test
